export const screen = {
  signIn: 'Sign-In',
  signUp: 'Sign-Up',
  homeStack: 'Home-Stack',
  profileStack: 'Profile-Stack',
  settingsStack: 'Settings-Stack',
  customerCare: 'Customer-Care',
  addProduct: 'Add-Product',
  productList: 'Product-List',
  bestDeals: 'Best-Deals',
  categories: 'Categories',
  search: 'Search',
  productDetail: 'Product-Detail',
  chat: 'Chat',
  cart: 'Cart',
  profile: 'Profile',
  settings: 'Settings',
  notifications: 'Notifications',
  userAgreement: 'User-Agreement',
  privacy: 'Privacy',
  paymentOptions: 'Payment-Options',
  giftCard: 'Gift-Card',
  about: 'About',
};
